theme: jekyll-theme-minimal

title: Search Algorithms
author: Jegors Čemisovs
email: jegors.cemisovs@outlook.lv
description: > # this means to ignore newlines until "baseurl:"
  This repository contains an implementation of two graphs search algorithms.
# social links
twitter_username: rabestro # DO NOT include the @ character, or else the build will fail!
github_username:  rabestro # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
